package pojo2;
// Generated Oct 19, 2020 4:38:15 PM by Hibernate Tools 4.3.1



/**
 * TblChef generated by hbm2java
 */
public class TblChef  implements java.io.Serializable {


     private String idChef;
     private String nama;
     private String pengalaman;

    public TblChef() {
    }

    public TblChef(String idChef, String nama, String pengalaman) {
       this.idChef = idChef;
       this.nama = nama;
       this.pengalaman = pengalaman;
    }
   
    public String getIdChef() {
        return this.idChef;
    }
    
    public void setIdChef(String idChef) {
        this.idChef = idChef;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPengalaman() {
        return this.pengalaman;
    }
    
    public void setPengalaman(String pengalaman) {
        this.pengalaman = pengalaman;
    }




}


